### ISSUE TITLE
Rename of "Blog"

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/BlazorStatic#14]
The name "Blog" is quite fitting for the primary usage of static site generators, but with the [BlazorStatic PR #13](https://github.com/tesar-tech/BlazorStatic/pull/13), we have introduced the option to add multiple "blogs". This is where the name "blog" fails to describe its broader purpose:

```csharp
builder.Services.AddBlogService<FrontMatter>()
    .AddBlogService<ProjectFrontMatter>(opt => {
        opt.MediaFolderRelativeToContentPath = null;
        opt.ContentPath = Path.Combine("Content", "Projects");
        opt.AddTagPagesFromPosts = false;
        opt.BlogPageUrl = "projects";
    });
//...
app.UseBlog<FrontMatter>();
app.UseBlog<ProjectFrontMatter>();
```

## Proposal:
- Rename "Blog" to "ContentSection":
  ```csharp
  builder.Services.AddContentSectionService<FrontMatter>()
    .AddContentSectionService<ProjectFrontMatter>(opt => {
        opt.MediaFolderRelativeToContentPath = null;
        opt.ContentPath = Path.combine("Content", "Projects");
        opt.AddTagPagesFromPosts = false;
        opt.ContentSectionPageUrl = "projects";
    });
  //...
  app.UseContentSection<FrontMatter>();
  app.UseContentSection<ProjectFrontMatter>();
  ``` 
- Rename `FrontMatter` to `BlogFrontMatter`.
- Keep `AddBlogService` and `UseBlog` with the generic variant for backward compatibility (but mark them as obsolete).
- Introduce `AddBlogService` and `UseBlog` as non-generic methods that will internally use `BlogFrontMatter` (if possible).

## Questions:
- Should we keep the default values of "ContentSection" for the blog (URL, content path, etc.)?
- Is there a better name than "ContentSection"?
- Is there anything else we should consider?

**Comment by junovell** [comment]
> Should we keep the default values of "ContentSection"

I think it would be nice to leave them for people who just want to make something quick.

> Is there a better name than "ContentSection"?

How about `BlazorStatic` or `StaticPages`?

```cs
builder.Services.AddBlazorStaticService<FrontMatter>();

// ...

app.UseBlazorStatic<FrontMatter>();
```

`BlazorStatic` would be nice because it's the same name as the project, but it might confuse people to think it's a native blazor service.

**Comment by tesar-tech** [comment]
We already have the `AddBlazorStaticService`, which goes with `UseBlazorStaticGenerator`, which is exactly what it does... `UseBlazorStatic` would be confusing...

`AddBlazorStatic` and `UseBlazorStaticGenerator` will work without "Blog", but not vice versa. The naming should send clear message that it is kind of "extension", something different, something extra (like blog naming did)

`AddStaticPagesService<FrontMatter>` and `UseStaticPages<Frontmatter>`  isn't bad, but is evoking more "general" concept, Some pages are already part of `AddBlazorStaticService` (for example index).  `ContentSection` is evoking "áh, so this is some sort of different section with a content, I need to add it to have that content..."

That's how I see it, but English is not my native language, so I am not sure if that makes the sense I am feeling there..

**Comment by junovell** [comment]
Sorry I forgot about that

`ContentSection` sounds weird and doesn't make much sense, that sentence is usually used to describe a part of the UI like the div containing the blog.

How about
- `AddBlazorStaticService` -> `AddBlazorStaticService`
- `AddBlogService` -> `AddStaticService`
- `UseBlog` -> `UseBlazorStatic`

I think that the methods' names should be similar to the project's name so that the user knows where they (the methods) came from without reading their description.

**Comment by sddania** [comment]
In my point of view, after closing the #13 PR this project has becoming a more generic SSG, so instead of `FrontMatter` type i would advise to change it as `ContentMetadata` and the service `BlogService` into `ContentService`.
I personally don´t like `ContentSection` as suggest initially because i could think it as a partial type of a hypothetical `Content` type, so i would also suggest to simply call it `Content` in order to make it oblivious.
I also suggest to rename the extensions like this
- AddBlazorStaticService -> AddBlazorStaticServices (maybe they'll become more?)
- AddBlogService -> AddContentService
- UseBlog -> UseContentMetadata

**Comment by tesar-tech** [comment]
I hear you both well, no `ContentSection` then. 

I like the `ContentService`, but I also agree with @MeltyObserver it should somehow contain the `BlazorStatic`.

- `AddBlazorStaticService` as is
- `AddBlazorStaticContentService` (I am also fine with `AddContentService`)
- `UseBlazorStaticGenerator` as is
- No `UseBlog` or other `Use`

Why no `UseBlog`? I think we can squeeze into `UseBlazorStaticGenerator`. The `UseBlog` itself has no meaning, it cannot be use without ensuing `UseBlazorStaticGenerator`. There is no use-case for calling `AddBlazorStaticContentService` (`AddBlogService`) and then not calling the `UseBlog`. `UseBlog` doesn't accept any arguments. 
Question is if we can "discover" StaticContentServicies and run the code (currently under `UseBlog` method) for every metadata type in `UseBlazorStaticGenerator`... wdyt on this? 


## FrontMatter vs ContentMetadata
`FrontMatter` wont be there anymore. It will be replaced with more concrete type of `BlogFrontMatter`. But the question is about `IFrontMatter` naming. I like the `IFrontMatter` more than `IContentMetadata`, because it really is a strongly typed front matter implementation. Frontmatter is established naming and would be unwise to not use it... `UseBlazorStaticContentService<IFrontMatter>`

**Comment by junovell** [comment]
the new names sound good to me, but I feel like `AddBlazorStaticContentService` is a bit too long.

> Question is if we can "discover" StaticContentServicies

why not just add them to a private list when `AddBlogService()` is called then iterate through them in `UseBlazorStaticGenerator()`?

I can write an example of this tomorrow if you want

> FrontMatter vs ContentMetadata

I believe the word "front matter" should stay, it's common to call the metadata at the top of a markdown file "front matter" ([even github calls it that](<https://docs.github.com/en/contributing/writing-for-github-docs/using-yaml-frontmatter>)) so we should stick to what's already established.

**Comment by tesar-tech** [comment]
It is a bit too long, true..

---

I haven't tested it yet. Please try it.

**Comment by junovell** [comment]
Sorry for the late response, but what do you mean by "try it"?

**Comment by tesar-tech** [comment]
I mean to try this:  `I can write an example of this tomorrow if you want`.

Try - because I am not sure if it's gonna work.

**Comment by junovell** [comment]
Well, it's a very basic solution [test/no-useblog](https://github.com/MeltyObserver/BlazorStatic/tree/test/no-useblog)

You can see the changes here https://github.com/MeltyObserver/BlazorStatic/commit/d6eaa5378fdb851ba70fb267b436d832e6ab522c

---

We can have a list of `IFrontMatter` only (`List<IFrontMatter>`), but that will [require reflections](<https://stackoverflow.com/a/232621/12429279>) which is inconvenient and hard to maintain

**Comment by tesar-tech** [comment]
Hm, that's easier than I thought. I will jump into it, do the rename and this simplification. 

Thank you for that. 

I also don't want to use reflection here
