### ISSUE TITLE
Suggestion: update the branding to remove versioning (outside of requirements)

### ISSUE THREAD

**Issue by patricktcoakley** [tesar-tech/BlazorStatic#42]
Maybe update the branding to remove the specific version to make it less confusing/tied to a specific .NET version:
<s>Embrace the capabilities of Blazor on .NET 8 to craft static websites.</s> -> Embrace the capabilities of Blazor on .NET to craft static websites.

Or something along those lines, and keep the .NET version tied to the requirements documentation where it actually makes sense.

**Comment by tesar-tech** [comment]
That's a good idea.

The version was there because with 8 it was the first dotnet that made it possible. Now it doesn't make sense.

I would go even farther and remove the .NET. Blazor wording is sufficient enough.

Mind to create the pr?
