### ISSUE TITLE
Discussion: Licensing

### ISSUE THREAD

**Issue by patricktcoakley** [tesar-tech/BlazorStatic#44]
Was there a particular reason AGPL v3 was chosen over some of the other available licenses? Some of the employers I've worked for or clients I've worked with would wholly be against the use of this project due to its licensing, regardless of whether or not it would directly impact them. I think BlazorStatic could be a great fit from certain kinds of projects, and while I am happy to support it as a contributor or use it on my own, it definitely makes it impossible for the majority of use outside of that.

**Comment by tesar-tech** [comment]
Thanks for bringing this to the light. 
No particular reason for the agpl licence. Not much effort was put into proper research and I don't have sufficient experience to foresee the implication...

So - what do you suggest?

**Comment by patricktcoakley** [comment]
So I encourage you to do your own comparisons because I don't want to come in with a specific license, but it was more to make you aware that licensing choices effect people's interests in using FOSS (at least in the US). Important things you want to ask yourself:

- Am I going to try and monetize this project down the road?
- Is having contribution back to the project very important to me?
- Do I want to stop large companies from making money off of my work?

[https://choosealicense.com/licenses/](https://choosealicense.com/licenses/) is a nice overview, but there are more nuances to some of the licenses.

Anyways, the main point I was trying to bring to discussion was that some companies flat out ban projects using certain licenses, especially any GPL, LGPL, or AGPL, even if the license won't restrict them from using it, their legal team can be very tough to convince otherwise. I would at least take a look at large .NET projects you like and respect to get some ideas.

**Comment by tesar-tech** [comment]
I see.

The approach I like is what comes with the [QuestPDF repository](https://github.com/QuestPDF/QuestPDF), where the product is published under a "dual" license—MIT for individuals and small companies, and a paid license for larger organizations. That makes sense to me. It keeps the project community-focused but restricts larger companies from profiting without giving back to the project.

For now, I would just change the license to MIT and consider monetization possibilities for upcoming versions.

How does that sound to you?

**Comment by patricktcoakley** [comment]
I would say the MIT license is a good default choice for open-source projects that want to have a hassle-free contribution process and to encourage people to start using your software without any real need for patent protections. MIT and Apache 2.0 are the most common I've seen in corporate environments that are usually allowlisted by default because the company doesn't run a risk from using it, and most aren't modifying it anyways so they just want to be able to use it without restrictions.

I think as long as you understand the risks and differences between what you currently have (AGPLv3) and MIT and you feel okay with it, it would probably be a better choice going forward.
