### ISSUE TITLE
Allow non url characters in tags

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/BlazorStatic#46]
creating a tag with `/` or `.` will cause troubles. For example `CI/CD` tag is currently impossible.

**Comment by patricktcoakley** [comment]
So I currently use [Zola](https://www.getzola.org) and would like to move to BlazorStatic in the future, but I just did some testing in Zola with both of these characters and it simply replaces non-alphanumeric characters with `-` for the URLs but will still display the original tag, which I think is a reasonable choice. 

So, for example, in the tags it will display "ci.cd", but when you click it the slug will be "/path/to/tags/ci-cd".  I did notice that if you have colliding tags like "ci.cd", "ci/cd", and "ci-cd" for one post, they all display fine but when you visit  "/path/to/tags/ci-cd" would list the same post three times, which might be confusing, but I think just swapping the character for a hyphen (`-`) is one of the easiest solutions.

What do you think?

**Comment by tesar-tech** [comment]
Interesting investigation. 

I was thinking more about url encode...
```
ci/cd---ci cd---cd.cd---c#---:---|---*  
becomes
ci%2Fcd---ci%20cd---cd.cd---c%23---%3A---%7C---%2A
```
which is also a valid filename. 

Doesn't produce nice urls (`tag/ci%2Fcd`), but avoids the conflicts you described..

**Comment by patricktcoakley** [comment]
I guess in my mind the odds of someone doing this on purpose are pretty low so it might be worth going with the common case and seeing if it comes up in the future. If you have strange URLs it might be harder for SEO-ness and things of that nature.

**Comment by tesar-tech** [comment]
I have implemented the url encode, but your comment inspired me to not set it in stone and include the Func to change it. More in the PR.
