### ISSUE TITLE
Deploy to Cloudflare Pages

### ISSUE THREAD

**Issue by patricktcoakley** [tesar-tech/BlazorStatic#51]
It would be nice to have a working pipeline to deploy to Cloudflare Pages in addition to Netlify since a lot of folks are using it to host their static sites.

**Comment by tesar-tech** [comment]
Yes. Do you have any experience with it?

**Comment by patricktcoakley** [comment]
Yeah I currently use it, I can take a look at what it takes. One thing I'm not sure about is how you do it as an "organization" like this, like  do you currently "own" the Netlify account? I wonder if there's a way to create a group for collaborators to have access to deployments, I will have to look into it.

**Comment by tesar-tech** [comment]
The netlify page runs under my "personal" account. But that's because I went the least resistance way.. 

One solution could be the email account with `@blazorstatic.net`, but that's bit stupid (you have to create new accounts).

We definitely don't want it to be tight up to personal accounts, ideally not even mine.

**Comment by patricktcoakley** [comment]
So I've been looking into this, and the easiest way is to create a main email account and then you're able to invite users by email to manage certain things. 

[Docs here](https://developers.cloudflare.com/fundamentals/setup/manage-members/manage/)

My understanding is you don't have to add billing information to a free plan, so I think it would be as easy as creating the email and then adding us via email with the correct permissions. 

If you want to try and tackle this yourself, it should be pretty straightforward with [this action](https://github.com/cloudflare/wrangler-action) since you can just point to your dist folder.
