### ISSUE TITLE
How to switch to local TailwindCSS?

### ISSUE THREAD

**Issue by lennartb-** [tesar-tech/BlazorStatic#53]
Hi,

I'm trying to move my blog from the mess of various JS SSG to BlazorStatic because I'm a lot more familiar with .NET than JS. I used `dotnet new BlazorStaticMinimalBlog` to bootstrap the project. I can generate a site with my MD files without issues, and now I want to move away from the Tailwind CDN thing to a local solution, as described in https://github.com/tesar-tech/BlazorAndTailwind

However I'm having a couple of issues. Mainly that there is no wwwroot or app.css to be found anywhere. If I add `wwwroot/app.css` to the root folder of the project and put 

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
into it, I already get `"tailwind" is not a known '@' directive.`  I've already run `tailwindcss init` and have a `tailwind.config.js`. When I run `tailwindcss -i ./wwwroot/app.css -o ./wwwroot/app.min.css` I get

```
tailwindcss.exe -i .\wwwroot\app.css -o .\wwwroot\app.min.css -w

Rebuilding...
ReferenceError: tailwind is not defined
    at C:\Users\lbrue\Source\Repos\lennartb.github.io.blazor\tailwind.config.js:9:24
    at evalModule (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:247313)
    at jiti (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:245241)
    at C:\snapshot\tailwindcss\lib\lib\load-config.js:52:26
    at loadConfig (C:\snapshot\tailwindcss\lib\lib\load-config.js:62:6)
    at Object.loadConfig (C:\snapshot\tailwindcss\lib\cli\build\plugin.js:135:49)
    at Object.getContext (C:\snapshot\tailwindcss\lib\cli\build\plugin.js:199:27)
    at C:\snapshot\tailwindcss\lib\cli\build\plugin.js:249:38
    at C:\snapshot\tailwindcss\lib\processTailwindFeatures.js:46:11
    at Object.Once (C:\snapshot\tailwindcss\lib\cli\build\plugin.js:257:19)
```

tailwind.config.js:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './Components/**/*.razor',
    ],
  theme: {
      extend: {
          colors: {
              primary: tailwind.colors.violet
          },
      },
  },
    plugins: [
        require('@tailwindcss/typography'),
    ],
}
```

What am I missing here?

**Comment by tesar-tech** [comment]
Hello.
We got this. I just need little bit more info

Easiest would be to share the project, can you do that?

**Comment by tesar-tech** [comment]
Ok. I tested the template and:

- the wwwroot folder is missing, which is kind of stupid.. we had it before, but for simplification we removed that.. there is also the need to specify the cdn or normal usage by parameters in `dotnet new` template.... Anyway adding the ./wwwroot/app.css is correct.
- I followed your steps and everything works as expected..

I think the error is

```
    colors: {
              primary: tailwind.colors.violet
          },
```

try to remove it and see the result..

**Comment by lennartb-** [comment]
Ah, thanks, removing the colors object from the config fixed it (should've read the error message closer, it's right there). I figured I could just move the script code from the `App.razor` to the tailwind.config.js, but apparently not. I left the script tag with the config there and added `<link rel="stylesheet" href="app.min.css">` instead of the CDN include and it works now.

The other error (`"tailwind" is not a known '@' directive.`) is unrelated then. [This](https://stackoverflow.com/questions/77390204/include-is-not-a-known-directive-message-in-vs-2022#comment136433506_77390204) comment for a similar error reveals that  VS can't know that the SASS syntax gets compiled with Tailwind, so the warning is probably okay.
